version: "3.8"

services:
  web:
    build: .
    image: iammahendravarma20/nextjs-monolith:latest
    container_name: nextjs-app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/myappdb

  mongo:
    image: mongo:6
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
